FROM asteere/scratch:scratch

MAINTAINER hydrate.with.koolaid@echostar.com

COPY ./bin /netlocation/bin

# Don't copy in the proprietary maxmind files because the container will be pushed to dockerhub
#COPY ./data /data

#CMD ["/netlocation/bin/netlocation"]


