[template]
src = "nginx.conf.tmpl"
dest = "/opt/nginx/nginx.conf"
keys = [
    "/raptor/netlocation",
]

# File ownership and mode information
owner = "root"
mode = "0777"

#check_cmd = "/usr/sbin/nginx -t"

# Send a signal to nginx to reload the configuration file
# From: http://blog.dixo.net/category/docker/
# TODO: Figure out how to pass in the instance id or create a script to send the signal and let it figure it out.
reload_cmd = "/opt/nginx/sendSignal.sh SIGHUP"
