[template]
src = "nginx.conf.tmpl"
dest = "/opt/nginx/nginx.conf"
keys = [
    "/raptor/netlocation",
]

# File ownership and mode information
owner = "root"
mode = "0777"

#check_cmd = "/usr/sbin/nginx -t"

# Send a signal to nginx to reload the configuration file
# From: http://blog.dixo.net/category/docker/
reload_cmd = "echo -e 'POST /containers/nginx/kill?signal=SIGHUP HTTP/1.0\r\n' | nc -U /var/run/docker.sock"
