#! /bin/bash

# Constants that regulate the monitor service
monitorService=monitor
monitorDir=/opt/monitor

# How often (seconds) should monitor check the consul health-checks
monitorRunChecksInterval=8

# How many netlocation failures before starting another service
criticalFailuresHighWaterMark=5

# How long (seconds) w/o critical errors before shutting down another service
errorFreePeriod=30

percentCpuSuccess=10
percentCpuWarning=20
# Anything above percentCpuWarning is considered a critical issue
